version: '3'
services:
  authsv:
    container_name: authsv
    build: .
    ports:
      - "8000:8000"
    command: npm run start-dev-authsv
    volumes:
      - .:/usr/src/app
    links:
      - mongo
    env_file:
      - ./auth-sv/dev.env

  apisv:
    container_name: apisv
    build: .
    ports:
      - "8001:8001"
    command: npm run start-dev-apisv
    volumes:
      - .:/usr/src/app
    links:
      - mongo
    env_file:
      - ./api-sv/dev.env
  
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
