version: '3'
services:
  app:
    container_name: gorev
    build: .
    ports: 
      - "8000:8000"
    links:
      - mongo
    env_file:
      - dev.env
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
